### ISSUE TITLE
Move to official GeoAlchemy2?

### ISSUE THREAD

**Issue by adrien-berchet** [WintorXR/GeoAlchemy2-MSSQL#1]
Hi @WAKayser 
I'm the main maintainer of [GeoAlchemy2](https://github.com/geoalchemy/geoalchemy2) and I just discovered your repository. Wouldn't it make sense to move it to the official repo so other people can use it? How much work do you think it would be?

**Comment by WAKayser** [comment]
Hey Adrien,

Thanks for all the work on GeoAlchemy2.

This is a very hacky implementation, where a lot of functionality can randomly error. 
The repo is mostly online, so that it is easy for me to use. 
I do not think it is reliable enough to warrant moving to the official repo.

**Comment by adrien-berchet** [comment]
Ok, I see, thanks for your quick answer!
So I guess that we could get some inspiration from your repository if we want to make GeoAlchemy2 compatible with MSSQL but we can't just merge it directly. I will just add a ref in an issue to your code and we'll see if someone wants to take some time to implement it :)
Thanks!
